batchsize: 32
num_class: 241
image_path: "/root/food_data/CNFOOD-241/train600x600/"
train_path: "/root/food_data/CNFOOD-241/train_n.txt"
test_path: "/root/food_data/CNFOOD-241/test_n.txt"

model_name: "densenet121.ra_in1k"
# weight_path: "/home/meow/cnfood241/food_code_cn241/outputs/densenet121.ra_in1k_288_cn241/model.pth"
weight_path: ""
store_name: "densenet121.ra_in1k_288_cn241"

img_size: 288
learning_rate: 0.0001
epoch: 50

is_test: false
use_pretrained: true
train_increased: false
