batchsize: 32
num_class: 241
image_path: "/root/food_data/CNFOOD-241/CNFOOD-241/train600x600/"
train_path: "/root/food_data/CNFOOD-241/CNFOOD-241/train_n.txt"
test_path: "/root/food_data/CNFOOD-241/CNFOOD-241/test_n.txt"

model_name: "maxvit_xlarge_tf_512.in21k_ft_in1k"
weight_path: ""
store_name: "maxvit_xlarge_tf_512.in21k_ft_in1k_512_cn241"

img_size: 512
learning_rate: 0.00001
epoch: 100

is_test: false
use_pretrained: true
train_increased: false