batchsize: 32
num_class: 241
image_path: "/root/food_data/CNFOOD-241/train600x600/"
train_path: "/root/food_data/CNFOOD-241/train_n.txt"
test_path: "/root/food_data/CNFOOD-241/test_n.txt"

model_name: "vgg16.tv_in1k"
# weight_path: "/home/meow/cnfood241/food_code_cn241/outputs/vgg16.tv_in1k_224_cn241/model.pth"
weight_path: ""
store_name: "vgg16.tv_in1k_224_cn241"

img_size: 224
learning_rate: 0.0001
epoch: 20

is_test: false
use_pretrained: true
train_increased: false
