batchsize: 32
num_class: 241
image_path: "/home/meow/my_data_disk_5T/food_classification/CNFOOD-241/train600x600/"
train_path: "/home/meow/my_data_disk_5T/food_classification/CNFOOD-241/train_n.txt"
test_path: "/home/meow/my_data_disk_5T/food_classification/CNFOOD-241/test_n.txt"

model_name: "convnextv2_nano.fcmae_ft_in1k"
weight_path: ""
store_name: "convnextv2_nano.fcmae_ft_in1k_448_cn241"

img_size: 448
learning_rate: 0.00001
epoch: 100

is_test: false
use_pretrained: true
train_increased: false
