batchsize: 4
num_class: 241
image_path: "/home/meow/my_data_disk_5T/food_classification/CNFOOD-241/train600x600/"
train_path: "/home/meow/my_data_disk_5T/food_classification/CNFOOD-241/train_n.txt"
test_path: "/home/meow/my_data_disk_5T/food_classification/CNFOOD-241/test_n.txt"

model_name: "beit_large_patch16_512.in22k_ft_in22k_in1k"
weight_path: ""
store_name: "beit_large_patch16_512.in22k_ft_in22k_in1k_512_cn241"

img_size: 512
learning_rate: 0.00001
epoch: 30

is_test: false
use_pretrained: true
