batchsize: 8
num_class: 241
image_path: "/home/meow/my_data_disk_5T/food_classification/CNFOOD-241/train600x600/"
train_path: "/home/meow/my_data_disk_5T/food_classification/CNFOOD-241/train_n.txt"
test_path: "/home/meow/my_data_disk_5T/food_classification/CNFOOD-241/test_n.txt"

model_name: "pvt_v2_b2_li.in1k"
weight_path: ""
store_name: "pvt_v2_b2_li.in1k_448_cn241"

learning_rate: 0.00001
epoch: 30

is_test: false
use_pretrained: true
