batchsize: 32
num_class: 101

image_path: "/home/meow/my_data_disk_5T/food_classification/TaiwaneseFood101/Taiwanese Food 101/images/"
train_path: "/home/meow/food_ai/food_classification/prenet_n/food_ai/prenet/T101/meta/train.txt"
test_path: "/home/meow/food_ai/food_classification/prenet_n/food_ai/prenet/T101/meta/test.txt"

model_name: "repvit_m0_9"
weight_path: ""
store_name: "repvit_m0_9_448_tw101"

learning_rate: 0.00001
epoch: 10

is_test: false
use_pretrained: true
