batchsize: 4
num_class: 241
image_path: "/home/meow/my_data_disk_5T/food_classification/CNFOOD-241/train600x600/"
train_path: "/home/meow/my_data_disk_5T/food_classification/CNFOOD-241/train_n.txt"
test_path: "/home/meow/my_data_disk_5T/food_classification/CNFOOD-241/test_n.txt"

model_name: "prenet"
# weight_path: "/home/meow/cnfood241/food_code_cn241/pretrained_models/resnet50-19c8e357.pth"
weight_path: "/home/meow/cnfood241/food_code_cn241/outputs/prenet_cn241/model.pth"
# weight_path: "/home/meow/cnfood241/food_code_cn241/outputs/prenet_cn241_30epoch_pretrain/model.pth"

store_name: "prenet_cn241_30epoch_pretrain"

img_size: 512
learning_rate: 0.0001
epoch: 3

is_test: false
use_pretrained: false
train_increased: true
